baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Damien Kazewych'
theme = 'dk'
copyright = '© Damien Kazewych 2023'

[params]
  splashSubtitle = 'Programmer, Drummer, and a few other things...'

[menu]
  [[menu.main]]
    name = "Projects"
    pre = "projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog/"
    weight = 3